name: meridian
description: "A timezone coordination tool."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Packages
  intl: ^0.19.0
  timezone: ^0.9.4
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  window_manager: ^0.4.3
  flutter_acrylic: ^1.1.4
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # We will add the icon here later manually,
  # but for Windows, we replace the .ico file directly.